# Generated by Django 2.1.2 on 2018-10-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
